### PR TITLE
added animation to the home image

### PR DESCRIPTION
**Pull request by Casmir293**
Added a blinking animation to the image on the home screen to make the UI more attractive. Kindly accept my PR.

### CODE REVIEW

**Comment by xamppsul** [comment]
@Casmir293 i will review your code, and also approve after successfully running your code base end to end, because this standart code fe verify account base on end to end, thanks

**Review by xamppsul — APPROVED** [review]
@Casmir293 thank you for contribute in this repo

**Comment by Casmir293** [comment]
@syamsulapp It's a pleasure. I look forward to making more contributions but in the meantime, you can follow me back here on GitHub.

**Comment by xamppsul** [comment]
> @syamsulapp It's a pleasure. I look forward to making more contributions but in the meantime, you can follow me back here on GitHub.

I have been follow back to your github profile

**Pull request merged**
